[
  {
    "id" : "31df2295-ec1e-47b6-909f-d30577471ae2",
    "prId" : 1613,
    "prUrl" : "https://github.com/digital-asset/daml/pull/1613",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "6e952942-e45b-4da9-9719-44f7bc224c9b",
        "parentId" : null,
        "authorId" : "eb431011-3221-41ae-bf30-e72dde278004",
        "body" : "This should remain as `INVALID_ARGUMENT` because the eventID didn't match the expected format.",
        "createdAt" : "2019-06-13T12:23:26Z",
        "updatedAt" : "2019-06-13T12:24:34Z",
        "lastEditedBy" : "eb431011-3221-41ae-bf30-e72dde278004",
        "tags" : [
        ]
      },
      {
        "id" : "8d626a77-f828-462a-a7d7-176595bde0da",
        "parentId" : "6e952942-e45b-4da9-9719-44f7bc224c9b",
        "authorId" : null,
        "body" : "that's hard to implement. the daml-on-x cannot validate eventId form, so it's not clear how to write the test for this. lets follow up on fixing this!",
        "createdAt" : "2019-06-13T12:30:40Z",
        "updatedAt" : "2019-06-13T12:30:41Z",
        "lastEditedBy" : null,
        "tags" : [
        ]
      },
      {
        "id" : "c5772116-ba7c-40c3-91d8-b6212597ddee",
        "parentId" : "6e952942-e45b-4da9-9719-44f7bc224c9b",
        "authorId" : "eb431011-3221-41ae-bf30-e72dde278004",
        "body" : "After discussing offline with @dajmaki, we agreed that `NOT_FOUND` is the correct error status, because the ledger api never specifies the format of the event id. Returning `INVALID_ARGUMENT` without telling users how to make it valid (i.e. by way of specifying the format) is not a nice thing to do :)",
        "createdAt" : "2019-06-13T12:46:51Z",
        "updatedAt" : "2019-06-13T12:46:52Z",
        "lastEditedBy" : "eb431011-3221-41ae-bf30-e72dde278004",
        "tags" : [
        ]
      }
    ],
    "commit" : "3d8f6d43a2bc2f58902cd0ded39ae5957e44251d",
    "line" : 14,
    "diffHunk" : "@@ -1,1 +106,110 @@      .fold(\n        Future.failed[Transaction](\n          Status.NOT_FOUND\n            .withDescription(s\"invalid eventId: ${request.eventId}\")\n            .asRuntimeException())) {"
  },
  {
    "id" : "fbeb7f4e-2d3d-401d-aeb7-d05b40e45349",
    "prId" : 1613,
    "prUrl" : "https://github.com/digital-asset/daml/pull/1613",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "05e00d6a-4e88-460e-b53f-e07c2b9619c0",
        "parentId" : null,
        "authorId" : "eb431011-3221-41ae-bf30-e72dde278004",
        "body" : "This should remain as `INVALID_ARGUMENT` because the eventID didn't match the expected format.",
        "createdAt" : "2019-06-13T12:23:38Z",
        "updatedAt" : "2019-06-13T12:24:34Z",
        "lastEditedBy" : "eb431011-3221-41ae-bf30-e72dde278004",
        "tags" : [
        ]
      }
    ],
    "commit" : "3d8f6d43a2bc2f58902cd0ded39ae5957e44251d",
    "line" : 5,
    "diffHunk" : "@@ -1,1 +87,91 @@      .fold(\n        Future.failed[TransactionTree](\n          Status.NOT_FOUND\n            .withDescription(s\"invalid eventId: ${request.eventId}\")\n            .asRuntimeException())) {"
  }
]