[
  {
    "id" : "f057768b-90e5-4be4-982c-d69bda04968f",
    "prId" : 36299,
    "prUrl" : "https://github.com/pandas-dev/pandas/pull/36299#pullrequestreview-564815711",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "8e1f4de3-0490-47bb-925e-d1830980db64",
        "parentId" : null,
        "authorId" : "7086d5c0-382b-4c41-b70d-144a07643f71",
        "body" : "can use double backticks fro Index",
        "createdAt" : "2021-01-09T22:31:32Z",
        "updatedAt" : "2021-03-02T20:43:24Z",
        "lastEditedBy" : "7086d5c0-382b-4c41-b70d-144a07643f71",
        "tags" : [
        ]
      },
      {
        "id" : "33b87ad7-954b-4833-8375-8e48527c382c",
        "parentId" : "8e1f4de3-0490-47bb-925e-d1830980db64",
        "authorId" : "f3e7d5fe-a112-47db-9178-8be42b4a8eab",
        "body" : "Done",
        "createdAt" : "2021-01-09T22:45:13Z",
        "updatedAt" : "2021-03-02T20:43:24Z",
        "lastEditedBy" : "f3e7d5fe-a112-47db-9178-8be42b4a8eab",
        "tags" : [
        ]
      }
    ],
    "commit" : "0af939d8a964a8039fc9f94444be14c18fbed1e4",
    "line" : 4,
    "diffHunk" : "@@ -1,1 +420,424 @@Indexing\n^^^^^^^^\n\n- Bug in :meth:`Index.union` dropping duplicate ``Index`` values when ``Index`` was not monotonic or ``sort`` was set to ``False`` (:issue:`36289`, :issue:`31326`)\n- Bug in :meth:`CategoricalIndex.get_indexer` failing to raise ``InvalidIndexError`` when non-unique (:issue:`38372`)"
  }
]