[
  {
    "id" : "0c368968-c8e2-4bed-ab60-4972f9c8bd20",
    "prId" : 26782,
    "prUrl" : "https://github.com/tensorflow/tensorflow/pull/26782#pullrequestreview-233420236",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "ded8ef3f-4ab7-4140-a9fe-de7b3cdd2ff7",
        "parentId" : null,
        "authorId" : "47966c70-ca9e-4f42-9f8b-165f9cd3ebaa",
        "body" : "is there a better error that explains that there is no file open?  e.g. FailedPreconditionError?  i understand wanting to keep it an IOError though.",
        "createdAt" : "2019-05-02T20:18:32Z",
        "updatedAt" : "2019-05-02T20:18:34Z",
        "lastEditedBy" : "47966c70-ca9e-4f42-9f8b-165f9cd3ebaa",
        "tags" : [
        ]
      },
      {
        "id" : "c8d1d150-3263-4cc1-82fa-3f7821bf1781",
        "parentId" : "ded8ef3f-4ab7-4140-a9fe-de7b3cdd2ff7",
        "authorId" : "8e22deea-6a17-4878-bc75-9e0ab793e0ac",
        "body" : "mmm dunno if TF has such thing on core c++ level, but from posix perspective this seems to be the right error to be returned, i.e. `Bad file number`",
        "createdAt" : "2019-05-03T11:12:04Z",
        "updatedAt" : "2019-05-03T11:12:06Z",
        "lastEditedBy" : "8e22deea-6a17-4878-bc75-9e0ab793e0ac",
        "tags" : [
        ]
      }
    ],
    "commit" : "693aa38472d90f55d2efd7807052c527032513a6",
    "line" : 5,
    "diffHunk" : "@@ -1,1 +107,111 @@  Status Close() override {\n    if (file_ == nullptr) {\n      return IOError(filename_, EBADF);\n    }\n    Status result;"
  }
]