[
  {
    "id" : "58fabb96-f28e-4780-a1bf-9fb573e196df",
    "prId" : 38626,
    "prUrl" : "https://github.com/pandas-dev/pandas/pull/38626#pullrequestreview-556643035",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "ee030341-2cae-4e07-ad6c-8b77ce2fa768",
        "parentId" : null,
        "authorId" : "6401b20f-26b1-4a7c-8433-dc789c15b9e1",
        "body" : "Good tests to prevent the issue from happening!",
        "createdAt" : "2020-12-21T20:27:34Z",
        "updatedAt" : "2020-12-22T03:47:14Z",
        "lastEditedBy" : "6401b20f-26b1-4a7c-8433-dc789c15b9e1",
        "tags" : [
        ]
      }
    ],
    "commit" : "8193ea1bbd1474de434e791dd33ceb05b1f3bd03",
    "line" : 6,
    "diffHunk" : "@@ -1,1 +155,159 @@\n\n@pytest.mark.parametrize(\"false_or_none\", [False, None])\nclass TestFalseOrNoneExpectedWarning:\n    def test_raise_on_warning(self, false_or_none):"
  }
]