[
  {
    "id" : "3dd936b1-16f5-4395-8db8-82a5e4c7e6b7",
    "prId" : 25040,
    "prUrl" : "https://github.com/pandas-dev/pandas/pull/25040#pullrequestreview-198442471",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "d3fc0e89-4093-430d-b75c-d25feb2a136e",
        "parentId" : null,
        "authorId" : "51189123-86a2-400a-9762-6816882b6f12",
        "body" : "Reference PR number as a comment below this function definition.",
        "createdAt" : "2019-01-31T06:40:58Z",
        "updatedAt" : "2019-02-01T19:32:31Z",
        "lastEditedBy" : "51189123-86a2-400a-9762-6816882b6f12",
        "tags" : [
        ]
      }
    ],
    "commit" : "0c1b914321cda59ee112abaccf031887c453252c",
    "line" : 41,
    "diffHunk" : "@@ -1,1 +238,242 @@                    reason=\"clipboard primitives not installed\")\n@pytest.mark.parametrize('data', [u'\\U0001f44d...', u'Ωœ∑´...', 'abcd...'])\ndef test_raw_roundtrip(data):\n    # PR #25040 wide unicode wasn't copied correctly on PY3 on windows\n    clipboard_set(data)"
  },
  {
    "id" : "98b5d642-790e-4de3-81b9-086c07cb8817",
    "prId" : 38350,
    "prUrl" : "https://github.com/pandas-dev/pandas/pull/38350#pullrequestreview-546701597",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "790f243f-6685-446e-a868-8b3c01445683",
        "parentId" : null,
        "authorId" : "8a5d728c-e241-4a19-b667-385656e4fd50",
        "body" : "looking at the CI the message being thrown is different",
        "createdAt" : "2020-12-08T01:47:08Z",
        "updatedAt" : "2020-12-08T19:20:42Z",
        "lastEditedBy" : "8a5d728c-e241-4a19-b667-385656e4fd50",
        "tags" : [
        ]
      },
      {
        "id" : "c060ff79-4538-483e-9e81-55ea65f8d19e",
        "parentId" : "790f243f-6685-446e-a868-8b3c01445683",
        "authorId" : "1aabfbf6-2ce5-4369-b43c-080661ffbe42",
        "body" : "I thought that the message didn't exist and wrote one, I'll fix them so they match with what's supposed to say. Where can I find the exact message? ",
        "createdAt" : "2020-12-08T02:23:15Z",
        "updatedAt" : "2020-12-08T19:20:42Z",
        "lastEditedBy" : "1aabfbf6-2ce5-4369-b43c-080661ffbe42",
        "tags" : [
        ]
      },
      {
        "id" : "132d9938-feee-4847-bd6c-bd827ffdde7a",
        "parentId" : "790f243f-6685-446e-a868-8b3c01445683",
        "authorId" : "8a5d728c-e241-4a19-b667-385656e4fd50",
        "body" : "run the code that throws the error",
        "createdAt" : "2020-12-08T02:39:45Z",
        "updatedAt" : "2020-12-08T19:20:42Z",
        "lastEditedBy" : "8a5d728c-e241-4a19-b667-385656e4fd50",
        "tags" : [
        ]
      }
    ],
    "commit" : "0389ace7fb8e3626710031994ed1ebea54e952c2",
    "line" : 7,
    "diffHunk" : "@@ -1,1 +241,245 @@        msg = \"clipboard only supports utf-8 encoding\"\n        # test case for testing invalid encoding\n        with pytest.raises(ValueError, match=msg):\n            df.to_clipboard(encoding=\"ascii\")\n        with pytest.raises(NotImplementedError, match=msg):"
  }
]