[
  {
    "id" : "935897e2-c72f-4e0d-a3c9-35e640a7a5cd",
    "prId" : 15359,
    "prUrl" : null,
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "864df2d6-1260-43f6-9ecb-7df5f684fb6c",
        "parentId" : null,
        "authorId" : "838eb58c-0fa8-4742-994f-a407c7183e57",
        "body" : "... and then the call to instantiate AnsibleModule can look like this:\n\n``` python\nself.module = AnsibleModule(argument_spec=merged_arg_spec, required_if=merged_required_if, **kwargs)\n```\n",
        "createdAt" : "2016-04-15T15:47:59Z",
        "updatedAt" : "2016-04-16T05:14:56Z",
        "lastEditedBy" : "838eb58c-0fa8-4742-994f-a407c7183e57",
        "tags" : [
        ]
      },
      {
        "id" : "f963cd79-3be2-4859-a13f-6d51bb8ca55e",
        "parentId" : "864df2d6-1260-43f6-9ecb-7df5f684fb6c",
        "authorId" : "3c2d2125-0d1f-41a8-b9f4-2c8913ca435d",
        "body" : "All references to kwargs have been removed.\n",
        "createdAt" : "2016-04-16T00:53:38Z",
        "updatedAt" : "2016-04-16T05:14:56Z",
        "lastEditedBy" : "3c2d2125-0d1f-41a8-b9f4-2c8913ca435d",
        "tags" : [
        ]
      }
    ],
    "commit" : "47620737fb8a93110765956f2f8bc4a885e09994",
    "line" : 129,
    "diffHunk" : "@@ -1,1 +127,131 @@                                    add_file_common_args=add_file_common_args,\n                                    supports_check_mode=supports_check_mode,\n                                    required_if=merged_required_if)\n\n        if not HAS_AZURE:"
  },
  {
    "id" : "4a787758-42e2-4325-96d7-0c68c1019668",
    "prId" : 32882,
    "prUrl" : "https://github.com/ansible/ansible/pull/32882#pullrequestreview-89685296",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "189e18ac-d6b2-4ba1-bdf0-61d5b809c2e0",
        "parentId" : null,
        "authorId" : "7c547162-2334-4e33-a627-e146840da9ec",
        "body" : "No need to create the same method, just call the one in basic.py from the module.",
        "createdAt" : "2018-01-04T23:53:16Z",
        "updatedAt" : "2018-01-18T07:47:50Z",
        "lastEditedBy" : "7c547162-2334-4e33-a627-e146840da9ec",
        "tags" : [
        ]
      },
      {
        "id" : "763746ce-dc13-4fd9-af46-9a87ce5794ca",
        "parentId" : "189e18ac-d6b2-4ba1-bdf0-61d5b809c2e0",
        "authorId" : "4ca8f397-6d40-4333-a80a-10b2991ebaee",
        "body" : "Here just move the invoking `self.module.deprecate` to `self.deprecate`.",
        "createdAt" : "2018-01-08T03:07:40Z",
        "updatedAt" : "2018-01-18T07:47:50Z",
        "lastEditedBy" : "4ca8f397-6d40-4333-a80a-10b2991ebaee",
        "tags" : [
        ]
      },
      {
        "id" : "2e9ff3da-221f-4e19-9ebc-0efa5e6c6efd",
        "parentId" : "189e18ac-d6b2-4ba1-bdf0-61d5b809c2e0",
        "authorId" : "7c547162-2334-4e33-a627-e146840da9ec",
        "body" : "You should still just call `self.module.deprecate`, no need to add another entry in the azure_rm_common when it already exists in basic.py",
        "createdAt" : "2018-01-10T02:05:39Z",
        "updatedAt" : "2018-01-18T07:47:50Z",
        "lastEditedBy" : "7c547162-2334-4e33-a627-e146840da9ec",
        "tags" : [
        ]
      },
      {
        "id" : "8f357d6a-2cb6-4678-bc4c-e4087b4647ac",
        "parentId" : "189e18ac-d6b2-4ba1-bdf0-61d5b809c2e0",
        "authorId" : "4ca8f397-6d40-4333-a80a-10b2991ebaee",
        "body" : "I want to keep the same experience as `self.fail` in the azure modules",
        "createdAt" : "2018-01-18T06:50:16Z",
        "updatedAt" : "2018-01-18T07:47:50Z",
        "lastEditedBy" : "4ca8f397-6d40-4333-a80a-10b2991ebaee",
        "tags" : [
        ]
      }
    ],
    "commit" : "e7be60bbc69c31a210fa35745a931d342534bb6f",
    "line" : 4,
    "diffHunk" : "@@ -1,1 +346,350 @@        self.module.fail_json(msg=msg, **kwargs)\n\n    def deprecate(self, msg, version=None):\n        self.module.deprecate(msg, version)\n"
  },
  {
    "id" : "d1b6c03a-7383-4321-aa7a-7e88689e988d",
    "prId" : 33298,
    "prUrl" : "https://github.com/ansible/ansible/pull/33298#pullrequestreview-79375175",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "709b64dd-abc5-486b-917b-e83b0a23d895",
        "parentId" : null,
        "authorId" : "7c547162-2334-4e33-a627-e146840da9ec",
        "body" : "Is there a reason why you removed the resource group not found part of the message, are these other errors that `CloudError` would expose?",
        "createdAt" : "2017-11-28T00:54:48Z",
        "updatedAt" : "2017-11-28T00:55:47Z",
        "lastEditedBy" : "7c547162-2334-4e33-a627-e146840da9ec",
        "tags" : [
        ]
      },
      {
        "id" : "8ca80d73-0269-4e59-a49c-2a54f4a55139",
        "parentId" : "709b64dd-abc5-486b-917b-e83b0a23d895",
        "authorId" : "1c0b9fee-cd4d-4c8e-adfc-511a934c15ca",
        "body" : "I think the origin error message is too subjective. There could be other reasons causing the exception. \r\n\r\nYes, I think `CloudError` can give us accurate error message. With the new change, the error is as below if using a non-existing resource group. \r\n\r\n\r\n```\r\nTASK [create storage account for function apps] *********************************************************************************************\r\nfatal: [localhost]: FAILED! => {\"changed\": false, \"msg\": \"Error retrieving resource group zhijzhao4 - Resource group 'zhijzhao4' could not be found.\"}\r\n```",
        "createdAt" : "2017-11-28T02:10:00Z",
        "updatedAt" : "2017-11-28T02:10:00Z",
        "lastEditedBy" : "1c0b9fee-cd4d-4c8e-adfc-511a934c15ca",
        "tags" : [
        ]
      },
      {
        "id" : "190e86a2-4808-4d3c-8e5f-6416d680efb8",
        "parentId" : "709b64dd-abc5-486b-917b-e83b0a23d895",
        "authorId" : "7c547162-2334-4e33-a627-e146840da9ec",
        "body" : "Sounds good to me, just wanted to check.",
        "createdAt" : "2017-11-28T02:21:47Z",
        "updatedAt" : "2017-11-28T02:21:47Z",
        "lastEditedBy" : "7c547162-2334-4e33-a627-e146840da9ec",
        "tags" : [
        ]
      }
    ],
    "commit" : "a281f81ec2fcc86d67a16a388682a6df41227273",
    "line" : 7,
    "diffHunk" : "@@ -1,1 +417,421 @@            return self.rm_client.resource_groups.get(resource_group)\n        except CloudError as cloud_error:\n            self.fail(\"Error retrieving resource group {0} - {1}\".format(resource_group, cloud_error.message))\n        except Exception as exc:\n            self.fail(\"Error retrieving resource group {0} - {1}\".format(resource_group, str(exc)))"
  }
]