[
  {
    "id" : "01d99afe-21f2-4b20-83c0-78965f33e034",
    "prId" : 8883,
    "prUrl" : "https://github.com/numpy/numpy/pull/8883#pullrequestreview-30391979",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "709a4205-a372-4c0d-bc89-2d04642a3b60",
        "parentId" : null,
        "authorId" : "589adf51-c83d-4d25-b0fa-10ed4e1f120a",
        "body" : "This causes cython to always check for raised exceptions when `PyFloat_AsDouble` returns -1.0.\r\n\r\nThis is what is recommended in the python API docs:\r\nhttps://docs.python.org/2/c-api/float.html#c.PyFloat_AsDouble ",
        "createdAt" : "2017-04-01T21:52:28Z",
        "updatedAt" : "2017-04-01T21:58:54Z",
        "lastEditedBy" : "589adf51-c83d-4d25-b0fa-10ed4e1f120a",
        "tags" : [
        ]
      }
    ],
    "commit" : "db2f5089fc5442ea8fca49188e2750a6c39b5664",
    "line" : 5,
    "diffHunk" : "@@ -1,1 +16,20 @@\n    # Float API\n    double PyFloat_AsDouble(object ob) except? -1.0\n    long PyInt_AsLong(object ob)\n"
  },
  {
    "id" : "354a2542-edb2-4de6-ad10-a69867d5feff",
    "prId" : 8884,
    "prUrl" : "https://github.com/numpy/numpy/pull/8884#pullrequestreview-30393124",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "f535c0bd-98f3-4277-adad-0221de19d303",
        "parentId" : null,
        "authorId" : "589adf51-c83d-4d25-b0fa-10ed4e1f120a",
        "body" : "`PyInt_AsLong` may have thrown an exception if it returns -1\r\nhttps://docs.python.org/2/c-api/int.html#c.PyInt_AsLong",
        "createdAt" : "2017-04-01T23:08:12Z",
        "updatedAt" : "2017-04-02T22:17:48Z",
        "lastEditedBy" : "589adf51-c83d-4d25-b0fa-10ed4e1f120a",
        "tags" : [
        ]
      }
    ],
    "commit" : "30ab8fc16883f111eba3c873eff32323eeb58747",
    "line" : 5,
    "diffHunk" : "@@ -1,1 +17,21 @@    # Float API\n    double PyFloat_AsDouble(object ob) except? -1.0\n    long PyInt_AsLong(object ob) except? -1\n\n    # Memory API"
  }
]