[
  {
    "id" : "70aaa16b-e95e-4982-9be7-e98d5dcf01a7",
    "prId" : 41586,
    "prUrl" : "https://github.com/pandas-dev/pandas/pull/41586#pullrequestreview-677763866",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "e37ad5cc-0465-4447-80f8-e1d800e1216c",
        "parentId" : null,
        "authorId" : "cc7022b2-2831-4c63-a4da-d18b0d342508",
        "body" : "Similar question as before: what's causing this test to raise a warning?",
        "createdAt" : "2021-06-07T18:41:26Z",
        "updatedAt" : "2021-06-07T18:45:44Z",
        "lastEditedBy" : "cc7022b2-2831-4c63-a4da-d18b0d342508",
        "tags" : [
        ]
      }
    ],
    "commit" : "e6f1c6b100e930260c1b82b5dbf103e34d1a677b",
    "line" : 5,
    "diffHunk" : "@@ -1,1 +423,427 @@\n    @pytest.mark.filterwarnings(\"ignore:Timestamp.freq is deprecated:FutureWarning\")\n    def test_reset_index_datetime(self, tz_naive_fixture):\n        # GH#3950\n        tz = tz_naive_fixture"
  }
]