[
  {
    "id" : "d7781649-c85f-4a5c-a0d9-10cfa220ceed",
    "prId" : 32198,
    "prUrl" : "https://github.com/pandas-dev/pandas/pull/32198#pullrequestreview-365242532",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "9f89d14c-007d-4f1f-be87-48b160e31ec0",
        "parentId" : null,
        "authorId" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "body" : "Is the tilde required here? Can you build this to see how this currently renders?",
        "createdAt" : "2020-02-26T06:08:54Z",
        "updatedAt" : "2020-02-26T06:08:56Z",
        "lastEditedBy" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "tags" : [
        ]
      },
      {
        "id" : "2e8922ee-6c7d-491e-b714-12c153697a6f",
        "parentId" : "9f89d14c-007d-4f1f-be87-48b160e31ec0",
        "authorId" : "5e0a8bfc-72c5-4411-9449-dc3f8405b416",
        "body" : "There are no problems when I build the documentation locally. But when I pushed it to pandas-dev, some tests failed (previous commit). However, after I added tilde, all checks passed. I thought it might be because the link was displayed as pandas.core.groupby.GroupBy.sum() instead of sum().",
        "createdAt" : "2020-02-26T13:31:06Z",
        "updatedAt" : "2020-02-26T13:31:07Z",
        "lastEditedBy" : "5e0a8bfc-72c5-4411-9449-dc3f8405b416",
        "tags" : [
        ]
      },
      {
        "id" : "3180bfa8-5f18-4720-bddc-122986f8cd95",
        "parentId" : "9f89d14c-007d-4f1f-be87-48b160e31ec0",
        "authorId" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "body" : "Does it actually render the link? This is different than how we link to GroupBy methods in our whatâ€™s new so not sure this would really solve the problem at hand (could be wrong)",
        "createdAt" : "2020-02-26T15:49:45Z",
        "updatedAt" : "2020-02-26T15:49:46Z",
        "lastEditedBy" : "5e8c5ef2-940b-436e-9c5f-98ae5460128c",
        "tags" : [
        ]
      },
      {
        "id" : "b12d064f-8668-40af-8f2a-948519d64b58",
        "parentId" : "9f89d14c-007d-4f1f-be87-48b160e31ec0",
        "authorId" : "b0c8ea7f-389d-4305-8e0a-a1a394b9fcc2",
        "body" : "iirc the tilde is used to just print the last element in the link text. So, without the tilde the text link would be `pandas.core.groupby.GroupBy.sum`, and with the tilde should be just `sum`.\r\n\r\nI don't think the doc build should fail in any of the cases. May be the error was something else?",
        "createdAt" : "2020-02-26T19:39:27Z",
        "updatedAt" : "2020-02-26T19:39:59Z",
        "lastEditedBy" : "b0c8ea7f-389d-4305-8e0a-a1a394b9fcc2",
        "tags" : [
        ]
      },
      {
        "id" : "ca60ca17-dc93-4725-a4ea-f6cbf28ed886",
        "parentId" : "9f89d14c-007d-4f1f-be87-48b160e31ec0",
        "authorId" : "5e0a8bfc-72c5-4411-9449-dc3f8405b416",
        "body" : "> Does it actually render the link?\r\n\r\nYes, it does render the link with and without the tilde.\r\n\r\n> iirc the tilde is used to just print the last element in the link text\r\n\r\nYes, it is correct. In the last commit the link is displayed as `sum()` instead of `pandas.core.groupby.GroupBy.sum`.\r\n\r\n> I don't think the doc build should fail in any of the cases. May be the error was something else?\r\n\r\nI checked today locally, there were no problems with building of the documentation, so the error might be not related.\r\n\r\nShould I push it without tilde? Or should I leave it like it is?\r\n",
        "createdAt" : "2020-02-26T21:07:49Z",
        "updatedAt" : "2020-02-26T21:07:49Z",
        "lastEditedBy" : "5e0a8bfc-72c5-4411-9449-dc3f8405b416",
        "tags" : [
        ]
      }
    ],
    "commit" : "c6b52c554201c1c5ed42fa4b83f4c0041197e472",
    "line" : 46,
    "diffHunk" : "@@ -1,1 +521,525 @@   df\n\nGrouping and then applying the :meth:`~pandas.core.groupby.GroupBy.sum` function to the resulting\ngroups.\n"
  }
]